version: "3"

services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
      - ./logs/ngrok.log:/app/ngrok.log
    ports:
      - 4040:4040

  web:
    build: .
    container_name: web
    volumes:
      - .:/app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=main.py
